apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-conf-notify"
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    port: {{ .Values.notify.port }}
    debug: {{ .Values.notify.debug }}

    kafka:
      address: "{{ .Release.Name }}-svc-kafka:9094"
      topic: "notify"

    telegram:
      token: {{ .Values.notify.telegram.token | quote }}
      trigger: {{ .Values.notify.telegram.trigger | quote }}
      aliases:
        username:
        {{- range $t := .Values.notify.telegram.aliasUserNameList }}
          {{ $t.uid | quote }}: {{ $t.name | quote }}
        {{- end }}

      templateToChats:
      {{- range $t := .Values.notify.telegram.templateToChatList }}
        {{ $t.templateName }}:
        {{- range $i := $t.idList }}
          - {{ $i.id }}
        {{- end }}
      {{- end }}
    
    templates:
    {{- range $t := .Values.notify.templateList }}
      {{ $t.name | quote }}: "{{ $t.message }}"
    {{- end }}
