apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-ss-kafka"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-svc-kafka"
  serviceName: "{{ .Release.Name }}-svc-kafka"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-svc-kafka"
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: "{{ .Release.Name }}-svc-kafka"
        image: {{ .Values.kafka.image }}
        ports:
        - containerPort: 9092
          name: "{{ .Release.Name }}-ss-kafka"
        env: 
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: 1@0.0.0.0:9093
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CFG_LOG_DIRS
          value: /tmp/logs
        - name: KAFKA_CFG_PROCESS_ROLES
          value: broker,controller
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://:9092,INTERNAL://:9094
        volumeMounts:
        - name: "{{ .Release.Name }}-storage"
          mountPath: /bitnami
      volumes:
      - name: "{{ .Release.Name }}-storage"
        persistentVolumeClaim:
          claimName: "{{ .Values.namespace }}-data-claim"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc-kafka"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Release.Name }}-svc-kafka"
spec:
  ports:
  - port: 9092
    name: "plaintext"
  - port: 9093
    name: "controller"
  - port: 9094
    name: "internal"
  clusterIP: None
  selector:
    app: "{{ .Release.Name }}-svc-kafka"
